name: mc

services:

    accesspanel:
        extends:
            file: docker-compose.base.yaml
            service: accesspanel
        build:
            context: .
            dockerfile: docker/accesspanel/Dockerfile
            target: build-dev
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.entrypoints=web"
            - "traefik.http.routers.whoami.rule=Host(`${EXTERNAL_DOMAIN_R}`) || Host(`${EXTERNAL_DOMAIN_P}`) || Host(`${EXTERNAL_DOMAIN_K}`)"
        volumes:
            - type: bind
              source: application
              target: /var/www/html

    traefik:
        extends:
            file: docker-compose.base.yaml
            service: traefik
        command:
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--log.level=DEBUG"
            - "--log.filepath=/var/log/traefik_dev.log"
            - "--accesslog=true"
            - "--accesslog.filepath=/var/log/access_dev.log"
            - "--providers.docker.network=mc_mc_net"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.web.address=:80"
        labels:
            - traefik.enable=true
            - traefik.http.routers.mydashboard.rule=Host(`${TRAEFIK_DASHBOARD_EXTERNAL_DOMAIN}`)
            - traefik.http.routers.mydashboard.service=api@internal

#    minecraft-r:
#        extends:
#            file: docker-compose.base.yaml
#            service: minecraft-r
#
#    minecraft-p:
#        extends:
#            file: docker-compose.base.yaml
#            service: minecraft-p

    minecraft-k:
        extends:
            file: docker-compose.base.yaml
            service: minecraft-k

    database:
        extends:
            file: docker-compose.base.yaml
            service: database
        ports:
            - "${DEV_DATABASE_EXTERNAL_PORT}:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        links:
            - database
        environment:
            PMA_HOST: ${DATABASE_HOST}
            PMA_USER: root
            PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            UPLOAD_LIMIT: 2000M
            MEMORY_LIMIT: 4000M
        ports:
            - "${DEV_PHPMYADMIN_EXTERNAL_PORT}:80"
        networks:
            - mc_net

networks:
    mc_net:
