name: mc

services:

    accesspanel:
        extends:
            file: docker-compose.yaml
            service: accesspanel
        volumes:
            - type: bind
              source: .
              target: /var/www/html

    database:
        extends:
            file: docker-compose.yaml
            service: database
        ports:
            - "${DEV_DATABASE_EXTERNAL_PORT}:3306"

#    minecraft-r:
#        extends:
#            file: docker-compose.yaml
#            service: minecraft-r
#
#    minecraft-p:
#        extends:
#            file: docker-compose.yaml
#            service: minecraft-p

    minecraft-k:
        extends:
            file: docker-compose.yaml
            service: minecraft-k

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: pmnator-phpmyadmin
        restart: unless-stopped
        links:
            - database
        environment:
            PMA_HOST: ${DATABASE_HOST}
            PMA_USER: root
            PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            UPLOAD_LIMIT: 2000M
            MEMORY_LIMIT: 4000M
        ports:
            - "${DEV_PHPMYADMIN_EXTERNAL_PORT}:80"
        networks:
            - mc_net

networks:
    mc_net:
