name: mc

services:

    accesspanel:
        build:
            context: .
            dockerfile: docker/accesspanel/Dockerfile
            target: build-dev
        container_name: accesspanel
        restart: unless-stopped
        tty: true
        stdin_open: true
        ports:
            - "20090:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`${EXTERNAL_DOMAIN_R}`) || Host(`${EXTERNAL_DOMAIN_P}`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"
        networks:
            - mc_net

    database:
        image: mariadb:latest
        container_name: database
        restart: unless-stopped
        volumes:
            - "database-data:/var/lib/mysql"
        environment:
            - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MARIADB_USER=mcpanel
            - MARIADB_PASSWORD=${DATABASE_PASSWORD}
            - MARIADB_DATABASE=mcpanel
        networks:
            - mc_net

    traefik:
        image: traefik:v3.3
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_LETSENCRYPT_EMAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "443:443"
            - "8080:8080"
        volumes:
            - "./var/letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - mc_net

    minecraft-r:
        image: 05jchambers/legendary-minecraft-purpur-geyser:latest
        container_name: minecraft-r
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - "./var/minecraft-r:/minecraft"
        ports:
            - "25566:25566"
            - "19133:19133/udp"
            - "8081:8081"
            - "25576:25576"
        environment:
            - TZ='Europe/Warsaw'
            - Port=25566
            - BedrockPort=19133
            - MaxMemory=8192
        networks:
            - mc_net

    minecraft-p:
        image: 05jchambers/legendary-minecraft-purpur-geyser:latest
        container_name: minecraft-p
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - "./var/minecraft-p:/minecraft"
        ports:
            - "25567:25567"
            - "19134:19134/udp"
            - "8082:8082"
            - "25577:25577"
        environment:
            - TZ='Europe/Warsaw'
            - Port=25567
            - BedrockPort=19134
            - MaxMemory=8192
        networks:
            - mc_net

volumes:
    database-data:

networks:
    mc_net:
